application: scrabit
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /static
  static_dir: static
- url: /cleaner
  script: main.py
  login: admin
- url: .*
  script: main.py
